-- Real C# inventory, config, battle and production UI; isolated Edit Mode services.
local registry=require('Core.SystemRegistry')(Services)
registry:Register('Config',require('Config.ConfigSystem'))
registry:Register('Battle',require('Game.Battle.BattleSystem'),{'Config'})
registry:Register('Equipment',require('Game.Equipment.EquipmentSystem'),{'Config'})
registry:Register('UI',require('UI.UISystem'),{'Config'})
local results={};local function test(name,run) run();results[#results+1]='PASS '..name end
local function near(a,b) assert(math.abs(a-b)<.00001,tostring(a)..' != '..tostring(b)) end
local ok,err=xpcall(function()
    registry:Start();local data=Services.Adventure;data:Reset(2)
    local battle,eq,ui=registry:Get('Battle'),registry:Get('Equipment'),registry:Get('UI')
    local mage=data:AddPartyActor(1,3);mage:SetMaxHP(100);mage:Restore()
    local warrior=data:AddPartyActor(2,6);warrior:SetMaxHP(100);warrior:Restore()
    eq:Start();eq:Grant(13,1)
    local function weapon(itemId)
        for i=0,eq.data.WeaponCount-1 do local w=eq.data:GetWeaponAt(i);if w.ItemId==itemId then return w end end
        error('Missing fixture weapon '..itemId)
    end
    local colossal=weapon(44)
    test('three melee categories contain two distinct configured tiers and only colossal blades have one socket',function()
        for category=3,5 do
            local rows={};for _,r in ipairs(eq.rules.weapons:All()) do if r.categoryId==category then rows[#rows+1]=r end end
            assert(#rows==2 and rows[1].level==1 and rows[2].level==2 and rows[2].damageMultiplier>rows[1].damageMultiplier)
            for _,r in ipairs(rows) do assert(#r.socketIds==(category==5 and 1 or 0));assert(r.skillIds[1]>=10) end
        end
    end)
    test('unmet requirements allow equipping, apply capped penalties, and leave support skills unchanged',function()
        assert(eq:Command('equip',1,colossal.Id,0,0));assert(eq.data:Equipped(1)==colossal)
        local r=eq.rules:Requirements(mage,colossal,battle.stats)
        assert(not r.met and r.missing==10 and r.hitLoss==30);near(r.damageScale,.35)
        local s=battle:Skill(mage,12);near(s.damageScale,1.65*.35);assert(s.hitChance==55)
        local guard=battle:Skill(mage,4);near(guard.damageScale,eq.rules.skills:Get(4).damageScale);assert(guard.hitChance==100)
        local heavy=weapon(45);assert(eq:Command('equip',1,heavy.Id,0,0));assert(eq.rules:Requirements(mage,heavy,battle.stats).hitLoss==40)
        assert(eq:Command('equip',1,weapon(41).Id,0,0));near(battle:Skill(mage,10).damageScale,1.3*.68)
        assert(eq:Command('equip',2,colossal.Id,0,0));local before=eq.rules:Requirements(warrior,colossal,battle.stats)
        assert(before.missing==3);warrior:AddTrait(1);local after=eq.rules:Requirements(warrior,colossal,battle.stats)
        assert(after.missing==1 and after.hitLoss==3);near(after.damageScale,.92)
        assert(eq:Command('equip',2,weapon(40).Id,0,0));assert(eq.rules:Requirements(warrior,weapon(40),battle.stats).met)
    end)
    test('thruster composes with requirement penalty, rejects other sockets and returns to inventory',function()
        assert(eq:Command('equip',1,colossal.Id,0,0));local before=battle:Skill(mage,12)
        assert(eq:Command('attach',1,colossal.Id,4,13));local after=battle:Skill(mage,12)
        near(after.damageScale,before.damageScale*1.35);assert(after.cost==before.cost and after.hitChance==before.hitChance)
        assert(eq.data:CountItem(13)==0 and colossal:GetRune(4)==13)
        local revision=eq.data.Revision;assert(not eq:Command('attach',1,weapon(1).Id,1,13));assert(not eq:Command('attach',1,weapon(40).Id,4,13));assert(eq.data.Revision==revision)
        assert(eq:Command('attach',1,colossal.Id,4,0));assert(eq.data:CountItem(13)==1)
        assert(eq:Command('attach',1,colossal.Id,4,13))
    end)
    test('equipped colossal attack deals resolved slash damage and spends its configured action budget',function()
        battle.board=require('Game.Battle.BattleBoard').Create(4,2,0)
        battle.data:Reset(1,18);battle.data:SetRandomSeed(2);battle.data:AddUnit(mage,1,0,0)
        local enemy=battle.data:AddEnemy(101,4,1,0);enemy:SetMaxHP(100);enemy:Restore()
        battle:NewRound();assert(battle:Active().Id==1)
        data:BeginEvent(1,1);data:ResolveChoice(1);data:BeginBattle()
        local skill=battle:Skill(mage,12);local effect=eq.rules.effects:Get(skill.effectIds[1])
        local amount=effect.amount:Evaluate(battle.stats:EffectVariables(mage,enemy,skill))
        local expected=math.max(1,math.floor(amount*skill.damageScale))
        assert(battle:TrySkill(12,101));assert(enemy.HP==100-expected,'seeded slash damage differs')
        assert(mage.AP==1 and mage.MainUsed and mage.ActionTemplateId==6 and mage:GetCooldown(12)==1)
    end)
    test('category controls, empty sockets and unmet-requirement equip work through Panel/Widget bindings',function()
        data:Reset(3);mage=data:AddPartyActor(1,3);mage:SetMaxHP(100);mage:Restore();eq:Start();eq:Grant(13,1)
        local adapter={};function adapter:SetEquipmentOpen(v)self.open=v end;function adapter:SendCommand(c)assert(c=='snapshot')end
        local panel=ui:Open('EquipmentWorkbench',{demo=adapter})
        for i=1,3 do panel.view.CategoryNext.onClick:Invoke() end
        assert(panel.view.CategoryText.text=='单手剑' and panel.view.Subtitle.text:find('Lv.1'))
        assert(panel.socketId==0 and not panel.view.Remove.interactable and panel.view.SocketTitle.text=='此武器没有改装槽')
        assert(panel.inventory[1].row.itemId==40 and panel.inventory[2].row.itemId==41)
        for _,row in ipairs(panel.inventory) do assert(row.view.Layout.ignoreLayout==(row.row==nil)) end
        panel.view.Equip.onClick:Invoke();assert(eq.data:Equipped(1).ItemId==40)
        panel.view.CategoryPrevious.onClick:Invoke();panel.view.CategoryPrevious.onClick:Invoke();panel.view.CategoryPrevious.onClick:Invoke()
        assert(panel.view.CategoryText.text=='全部武器')
        for i=1,5 do panel.view.CategoryNext.onClick:Invoke() end
        assert(panel.view.Requirements.text:find('可装备') and panel.view.Equip.interactable)
        panel.view.Equip.onClick:Invoke();panel.options[1].view.Button.onClick:Invoke()
        assert(eq.data:Equipped(1).ItemId==44 and eq.data:Equipped(1):GetRune(4)==13)
        assert(panel.view.Stats.text:find('伤害 ×0.78') and panel.view.SocketText1.text:find('推进器'))
        ui:Close('EquipmentWorkbench');assert(not adapter.open and not Services.UI.IsWorldPaused)
    end)
end,debug.traceback)
registry:Shutdown();if not ok then error(err,0) end
return table.concat(results,'\n')
