-- Isolated Edit Mode LuaEnv using real C# actors and the production battle commands.
local config=require('Config.ConfigSystem')()
config:OnInit({services=Services})
local Stats=require('Game.Battle.CombatStats')
local stats=Stats(config,Services.Adventure.Equipment)
local Actor=CS.ProjectY.Data.CombatActorData
local results={}
local function test(name,body) body();results[#results+1]='PASS '..name end
local function hero(id)
    local actor=Actor(id,1);actor:SetMaxHP(stats:MaximumHP(actor));actor:Restore()
    actor.Growth:Initialize(1,30,0,0)
    actor.Growth:AddExperience(1);actor.Growth:AdvanceLevel(1,0,0,true)
    actor.Growth:AddOffer(201);actor.Growth:LearnOffer(201)
    return actor
end
local function animal(id,species,seed)
    local row=stats.animals.species:Get(species)
    local actor=Actor(id,row.unitId);actor:InitializeAnimal(species,seed or 1)
    actor:SetMaxHP(stats:MaximumHP(actor));actor:Restore();actor:Deploy(2,0,0)
    return actor
end
test('configured retry delay is shared by all characters and survives deployment',function()
    local target=animal(101,1);local a,b=hero(1),hero(2)
    target:DelayTaming(config:GetTable('AnimalSpeciesTable'):Get(1).tameRetryTurns)
    assert(target.TameRetryTurns==3 and not stats.animals:CanTame(a,target) and not stats.animals:CanTame(b,target))
    target:Deploy(2,0,0);assert(target.TameRetryTurns==3)
    target:AdvanceTamingRound();target:AdvanceTamingRound();assert(not stats.animals:CanTame(a,target))
    target:AdvanceTamingRound();assert(stats.animals:CanTame(a,target))
end)
test('exploration clock accumulates movement time, preserves partial rounds and never advances while idle',function()
    local state=CS.ProjectY.Data.MapAreaStateData(1,20,1)
    local group=state:AddEncounter(1,201);local target=group:AddEnemy(101,201,3,0);target:InitializeAnimal(1,1);target:DelayTaming(3)
    state:DeployMembers({1},{1});assert(state:AdvanceExplorationRounds(100,1,.25)==0)
    state:SetSquadRoute({2,3,4,5})
    for i=1,2 do state:AdvanceExplorationRounds(.25,1,.25);state:Advance(.25,.25) end
    assert(state.WorldRound==0 and target.TameRetryTurns==3)
    state:Stop();assert(state:AdvanceExplorationRounds(100,1,.25)==0)
    state:SetSquadRoute({4,5})
    for i=1,2 do state:AdvanceExplorationRounds(.25,1,.25);state:Advance(.25,.25) end
    assert(state.WorldRound==1 and target.TameRetryTurns==2)
    state:CompleteWorldRound();assert(state.WorldRound==2 and target.TameRetryTurns==1)
    state:CompleteWorldRound();assert(target.TameRetryTurns==0)
end)
test('rider retains animal identity and injured HP; lethal mount hit discards overflow',function()
    local rider,mount=hero(1),animal(101,1)
    mount:Damage(7);local hp=mount.HP;local riderHP=rider.HP
    rider:TameAndRide(mount,0)
    assert(rider.MountedAnimal==mount and mount.AnimalOwnerId==rider.Id and mount.HP==hp)
    rider:Damage(3);assert(mount.HP==hp-3 and rider.HP==riderHP)
    rider:Damage(100000);assert(mount.HP==0 and rider.MountedAnimal==nil and rider.HP==riderHP)
    rider:Damage(2);assert(rider.HP==riderHP-2)
end)
local function battle(rider,enemy,board)
    local b=require('Game.Battle.BattleSystem')()
    b.stats=stats;b.skills=config:GetTable('CombatSkillTable');b.effects=config:GetTable('CombatEffectTable');b.encounters=config:GetTable('CombatEncounterTable')
    b.data=CS.ProjectY.Data.BattleData();b.data:Reset(201,30);b.data:AddUnit(rider,1,-2,0);b.data:AddUnit(enemy,2,0,0)
    b.data:BeginRound();b.data:AddTurn(rider.Id);b.data:AddTurn(enemy.Id);b.data:SelectTurn(0);rider:BeginTurn(4)
    b.board=board or require('Game.Battle.BattleBoard').Create(5,1,0)
    b.Changed=require('Core.Signal')(function(message)error(message)end)
    return b
end
test('combat taming consumes action, immediately mounts and ends last-hostile combat once',function()
    local rider,enemy=hero(1),animal(101,1)
    local b=battle(rider,enemy);rider:Move(-1,0,1)
    assert(b:CanUseSkill(201,101));assert(b:TrySkill(201,101))
    assert(rider.MountedAnimal==enemy and rider.Q==0 and rider.R==0 and rider.MainUsed and rider.AP==1)
    assert(b.data.Winner=='victory' and #b:Units()==1)
end)
test('bond gates species skills; longer horse charge increases real damage',function()
    local function strike(distance)
        local rider,mount=hero(1),animal(201,1);rider:TameAndRide(mount,0)
        local enemy=Actor(101,4);enemy:SetMaxHP(200);enemy:Restore()
        local b=battle(rider,enemy)
        enemy:Deploy(2,-2+distance,0)
        assert(not b:SkillBudget(202),'Cavalry skill must be locked before enough shared battles')
        stats.animals:BattleBond(rider)
        assert(b:TrySkill(202,101));assert(rider.Q==-3+distance)
        return 200-enemy.HP
    end
    assert(strike(4)>strike(2))
end)
test('rabbit jump crosses low blocked cells, respects AP and rejects occupied or distant landing',function()
    local rider,mount=hero(1),animal(201,3);rider:TameAndRide(mount,10)
    local enemy=Actor(101,4);enemy:SetMaxHP(200);enemy:Restore()
    local b=battle(rider,enemy);b.board:Find(-1,0).blocked=true
    assert(not b:CanUseSkillAt(204,0,0))
    assert(not b:CanUseSkillAt(204,2,0))
    assert(b:TrySkillAt(204,1,0));assert(rider.Q==1 and rider.R==0 and rider.AP==2 and rider.Moved)
    assert(rider.MovementStyle=='leap' and rider.MovementSequence>0)
end)
test('active skill pool can offer taming only above configured affinity threshold',function()
    local rider=hero(1)
    local pool=stats.growth.pools:Get(201);assert(pool.minValue==5 and pool.attributeId==18)
    local actor=Actor(20,1);actor.Growth:Initialize(31,30,0,0)
    actor.Growth:InvestAttribute('animalAffinity',1,5)
    local lookup={Template=function()return {} end,Get=function(_,a,name)return name=='animalAffinity' and a.Growth:GetAttribute(name) or 0 end,
        equipment={SkillIds=function()return {101,102,103,104,105,106,107,108} end}}
    local offers=stats.growth:Draw(actor,lookup);assert(#offers==1 and offers[1]==201)
end)
config:OnShutdown()
return table.concat(results,'\n')
