-- Targeted real C# grid/equipment + production Lua commands and Panel. Run after generating xLua bindings and Inventory prefab.
local registry=require('Core.SystemRegistry')(Services)
registry:Register('Config',require('Config.ConfigSystem'))
registry:Register('MapArea',require('Game.MapArea.MapAreaSystem'),{'Config'})
registry:Register('Battle',require('Game.Battle.BattleSystem'),{'Config'})
registry:Register('Equipment',require('Game.Equipment.EquipmentSystem'),{'Config'})
registry:Register('UI',require('UI.UISystem'),{'Config'})
local results={};local function test(name,run) run();results[#results+1]='PASS '..name end
local function grid(w,h,shapes)
    local data=CS.ProjectY.Data.EquipmentData();data.Grid:Configure(w,h)
    for id,shape in pairs(shapes) do data.Grid:Define(id,shape[1],shape[2]) end
    return data
end
local ok,err=xpcall(function()
    registry:Start()
    test('rotation, overlap and bounds preserve positions on rejected moves',function()
        local d=grid(4,3,{{3,1},{1,2}});local a,b=d:AddWearable(1),d:AddWearable(2)
        assert(d:Move('g'..a.Id,0,0,true));local p=d.Grid:Find('g'..a.Id)
        assert(p.Width==1 and p.Height==3 and p.Rotated)
        local rev=d.Revision;assert(not d:Move('g'..a.Id,3,0,true));assert(not d:Move('g'..b.Id,4,0,false))
        assert(d.Revision==rev and d.Grid:Find('g'..a.Id).X==0 and d.Grid.Count==2)
    end)
    test('full bag rejects a larger old weapon without changing ownership',function()
        local d=grid(2,2,{{2,2},{1,1},{1,1}});local large=d:AddWeapon(1);assert(d:Equip(1,large.Id))
        local small=d:AddWeapon(2);for i=1,3 do d:AddWearable(3) end
        local rev=d.Revision;assert(not d:CanEquip(1,small.Id) and not d:Equip(1,small.Id))
        assert(d.Revision==rev and d:Equipped(1).Id==large.Id and small.OwnerActorId==0 and d.Grid.Count==4)
        assert(not d:Equip(1,0) and large.OwnerActorId==1)
    end)
    test('offhand shield/weapon exchange is atomic when the bag is full',function()
        local d=grid(2,2,{{2,2},{1,1},{1,1}});local shield=d:AddWearable(1);assert(d:Wear(1,'offhand',shield.Id))
        local sword=d:AddWeapon(2);local fillers={};for i=1,3 do fillers[i]=d:AddWearable(3) end
        local rev=d.Revision
        assert(not d:CanEquipOffhand(1,sword.Id) and not d:EquipOffhand(1,sword.Id))
        assert(d.Revision==rev and d:Offhand(1)==nil and d:Worn(1,'offhand').Id==shield.Id and sword.Hand=='')
        for i,slot in ipairs({'head','body','legs'}) do assert(d:Wear(2,slot,fillers[i].Id)) end
        assert(d:EquipOffhand(1,sword.Id));assert(d:Worn(1,'offhand')==nil and sword.Hand=='offhand' and shield.OwnerActorId==0)
        assert(d:Wear(1,'offhand',shield.Id));assert(d:Offhand(1)==nil and sword.Hand=='' and d.Grid:Find('w'..sword.Id))
    end)
    test('full bag reload reuses the reserve magazine rectangle and retains rounds',function()
        local d=grid(2,1,{{1,1},{1,1},{1,1}});local gun=d:AddWeapon(1);assert(d:Equip(1,gun.Id))
        local old=d:AddMagazine(2,3,12,5);assert(d:AttachMagazine(gun.Id,old.Id))
        local spare=d:AddMagazine(2,3,12,12);d:AddStack(3,6)
        local position=d.Grid:Find('m'..spare.Id)
        assert(d:CanAttachMagazine(gun.Id,spare.Id) and d:AttachMagazine(gun.Id,spare.Id))
        assert(old.Rounds==5 and d:MagazineWeapon(old.Id)==0 and gun.MagazineId==spare.Id)
        assert(d.Grid:Find('m'..old.Id).X==position.X and not d:AttachMagazine(gun.Id,0))
        assert(d:FillMagazine(old.Id)==6 and d:CountItem(3)==0 and d.Grid:Find('s3')==nil)
    end)
    test('rune exchange can use the last incoming stack rectangle and refuses overflowing removal',function()
        local d=grid(1,1,{{1,1},{1,1},{1,1}});local w=d:AddWeapon(1);assert(d:Equip(1,w.Id))
        d:AddStack(2,1);assert(d:SetRune(w.Id,1,2));d:AddStack(3,1)
        assert(d:SetRune(w.Id,1,3) and d:CountItem(2)==1 and d:CountItem(3)==0)
        local rev=d.Revision;assert(not d:SetRune(w.Id,1,0));assert(d.Revision==rev and w:GetRune(1)==3)
    end)
    local data=Services.Adventure;local eq,battle,ui=registry:Get('Equipment'),registry:Get('Battle'),registry:Get('UI')
    data:Reset(41);local actor=data:AddPartyActor(1,1);actor:SetMaxHP(battle.stats:MaximumHP(actor));actor:Restore()
    local other=data:AddPartyActor(2,3);other:SetMaxHP(battle.stats:MaximumHP(other));other:Restore();eq:Start()
    local model=require('Game.Equipment.InventoryModel').New(eq,battle.stats)
    local function item(id)
        for _,row in ipairs(model:Rows(1)) do if row.itemId==id then return row end end
        error('Fixture missing item '..id)
    end
    test('wearables and shield are placed, slots reject mismatches, rings affect only the owner',function()
        assert(eq.data.WearableCount==7 and eq.data.Grid.Width==12 and eq.data.Grid.Height==10)
        local left,right=item(53),item(54);local strength=battle.stats:Get(actor,'strength');local intellect=battle.stats:Get(actor,'intellect')
        local otherStrength=battle.stats:Get(other,'strength');local rev=eq.data.Revision
        assert(not model:Command('equip:head',1,left.key,0,0,false) and eq.data.Revision==rev)
        assert(model:Command('equip:leftRing',1,left.key,0,0,false));assert(model:Command('equip:rightRing',1,right.key,0,0,false))
        assert(battle.stats:Get(actor,'strength')==strength+2 and battle.stats:Get(actor,'intellect')==intellect+2)
        assert(battle.stats:Get(other,'strength')==otherStrength)
        assert(model:Command('move',1,left.key,left.x,left.y,false))
        assert(eq.data:Worn(1,'leftRing')==nil and battle.stats:Get(actor,'strength')==strength and eq.data:Worn(1,'rightRing')~=nil)
        local armor=item(52);local hp,max=actor.HP,actor.MaxHP;local defense=battle.stats:Get(actor,'defense')
        assert(model:Command('equip:body',1,armor.key,0,0,false))
        assert(battle.stats:Get(actor,'defense')==defense+3 and actor.MaxHP==battle.stats:MaximumHP(actor) and actor.MaxHP-actor.HP==max-hp)
    end)
    test('real commands equip dual swords, replace a shield and reject conflicting two-hand weapons',function()
        local main,off,large,shield=item(40),item(41),item(42),item(57)
        assert(model:Command('equip:weapon',1,main.key,0,0,false))
        assert(model:Command('equip:offhand',1,off.key,0,0,false))
        assert(eq.data:Equipped(1).Id==main.id and eq.data:Offhand(1).Id==off.id)
        assert(not model:Command('equip:weapon',1,large.key,0,0,false))
        local defense=battle.stats:Get(actor,'defense')
        assert(model:Command('equip:offhand',1,shield.key,0,0,false))
        assert(eq.data:Offhand(1)==nil and eq.data.Grid:Find(off.key) and battle.stats:Get(actor,'defense')==defense+3)
        assert(not model:Command('equip:weapon',1,large.key,0,0,false))
        assert(model:Command('unequip',1,shield.key,0,0,false))
        assert(model:Command('equip:weapon',1,large.key,0,0,false))
        assert(not model:Command('equip:offhand',1,off.key,0,0,false))
        assert(not model:Command('equip:offhand',1,shield.key,0,0,false))
    end)
    test('unfittable loot remains unclaimed with no partial grant',function()
        local areas=registry:Get('MapArea')
        assert(areas:Enter({id=77,pointId=11,areaConfigId=1,source={regionId=1,regionConfigId=1,regionType=1,q=0,r=0,height=1,biomeWeights={{regionType=1,weight=1}}}},41))
        eq:InitializeLoot(areas);local state=areas.data.Active;local loot=state:GetLootAt(0)
        state:DeployMembers({actor.Id},{loot.CellIndex});areas:RevealSquad(areas:ActiveLayout(),state)
        while eq:CanGrant({53},{1}) do assert(eq:Grant(53,1)) end
        local rev=eq.data.Revision;assert(not eq:Loot(areas,loot.Id));assert(not loot.Looted and eq.data.Revision==rev)
        assert(areas:Leave())
    end)
    test('inventory Panel renders snapshot, changes real equipment and releases its pause lease',function()
        data:Reset(42);actor=data:AddPartyActor(1,1);actor:SetMaxHP(battle.stats:MaximumHP(actor));actor:Restore();eq:Start()
        local adapter={};function adapter:SetEquipmentOpen(value) self.open=value end;function adapter:SendCommand(command) assert(command=='snapshot') end
        local panel=ui:Open('Inventory',{demo=adapter});assert(adapter.open and Services.UI.IsWorldPaused)
        for _,row in ipairs(panel.rows) do assert(type(row.rotated)=='boolean' and type(row.equipMask)=='number') end
        local head=item(51);panel.selected=head.key;panel:Refresh();panel.view.Equip.onClick:Invoke()
        assert(eq.data:Worn(1,'head').ItemId==51 and panel.view.Unequip.interactable)
        panel.view.Unequip.onClick:Invoke();assert(eq.data:Worn(1,'head')==nil)
        local off=item(40);panel.selected=off.key;panel:Refresh();panel.view.Slot_offhand.onClick:Invoke()
        assert(eq.data:Offhand(1).Id==off.id and panel.view.Character~=nil)
        panel.view.Unequip.onClick:Invoke();assert(eq.data:Offhand(1)==nil)
        panel.view.Workbench.onClick:Invoke();assert(adapter.open and Services.UI.IsWorldPaused)
        ui:Close('EquipmentWorkbench');assert(not adapter.open and not Services.UI.IsWorldPaused)
        panel=ui:Open('Inventory',{demo=adapter});panel.view.Close.onClick:Invoke();assert(not adapter.open and not Services.UI.IsWorldPaused)
    end)
    test('offhand skill deals resolved damage and spends secondary action budget',function()
        data:Reset(43);actor=data:AddPartyActor(1,3);actor:SetMaxHP(100);actor:Restore();eq:Start()
        local main,off=item(40),item(41)
        assert(eq:Command('equip',1,main.id,0,0));assert(eq:Command('equip_offhand',1,off.id,0,0))
        battle.board=require('Game.Battle.BattleBoard').Create(4,2,0)
        battle.data:Reset(1,18);battle.data:SetRandomSeed(2);battle.data:AddUnit(actor,1,0,0)
        local enemy=battle.data:AddEnemy(101,4,1,0);enemy:SetMaxHP(100);enemy:Restore()
        battle:NewRound();assert(battle:Active().Id==1)
        data:BeginEvent(1,1);data:ResolveChoice(1);data:BeginBattle()
        local skill=battle:Skill(actor,13);local effect=eq.rules.effects:Get(skill.effectIds[1])
        local amount=effect.amount:Evaluate(battle.stats:EffectVariables(actor,enemy,skill))
        local expected=math.max(1,math.floor(amount*skill.damageScale));local ap=actor.AP
        assert(battle:TrySkill(13,101));assert(enemy.HP==100-expected)
        assert(actor.AP==ap-skill.cost and not actor.MainUsed and actor.ActionTemplateId==7)
    end)
end,debug.traceback)
registry:Shutdown()
if not ok then error(err,0) end
return table.concat(results,'\n')
