local registry=require('Core.SystemRegistry')(Services)
registry:Register('Config',require('Config.ConfigSystem'))
registry:Register('PlayerModel',require('Game.PlayerModelSystem'),{'Config'})
registry:Register('Map',require('Game.Map.MapSystem'),{'Config'})
registry:Register('MapArea',require('Game.MapArea.MapAreaSystem'),{'Config'})
registry:Register('Battle',require('Game.Battle.BattleSystem'),{'Config'})
registry:Register('Equipment',require('Game.Equipment.EquipmentSystem'),{'Config'})
registry:Register('Growth',require('Game.Progression.GrowthSystem'),{'Battle'})
registry:Register('AdventureEvents',require('Game.Adventure.EventSystem'),{'Battle','PlayerModel','Growth','Equipment'})
registry:Register('Adventure',require('Game.Adventure.AdventureSystem'),{'Map','MapArea','AdventureEvents','Equipment'})
registry:Register('UI',require('UI.UISystem'),{'Adventure'})
local results={};local function test(name,fn) fn();results[#results+1]='PASS '..name end
local ok,err=xpcall(function()
    registry:Start();local adventure=registry:Get('Adventure');adventure:Start(412)
    local forest;for _,site in ipairs(adventure.sites) do if site.areaConfigId==20 then forest=site end end
    assert(adventure:Visit(assert(forest).id))
    local eq,areas,ui=adventure.equipment,adventure.areas,registry:Get('UI');local state=areas.data.Active
    eq.data:Clear();eq.data.Grid:Configure(12,10)
    for _,itemId in ipairs({2,51,31,53}) do assert(eq:Grant(itemId,itemId==31 and 12 or 1)) end
    state:AddLoot(state.CellIndex,100,'林间遗留的物资',{40,31,51,1,2,11},{1,7,1,1,1,1},true)
    local source=state:GetLootAt(state.LootCount-1)
    local adapter={}
    function adapter:SetEquipmentOpen(value) self.open=value end
    function adapter:SendCommand(command) assert(command=='snapshot') end
    assert(adventure:AreaCommand('area_loot',source.Id))
    local session=eq.worldLoot.session;local panel=ui:Open('Loot',{demo=adapter});session:Present()
    test('real panel opens paused with two grids and rejects hidden-item pointer drags',function()
        assert(adapter.open and Services.UI.IsWorldPaused and #panel.bagRows==4 and #panel.lootRows==6)
        local item=session:GetAt(0);local revision=eq.data.Revision
        DragLoot(panel.reference,item.Key,10,5,false)
        CheckLootDrag(panel.reference,false)
        assert(eq.data.Revision==revision and item.Count==1 and not item.Revealed)
        DropInLoot(panel.reference,'s31',1,0,false)
        assert(eq.data.Revision==revision and eq.data:CountItem(31)==12,'Cannot merge into an unsearched item')
        panel:Tick(0,.45);assert(item.Progress>0 and not item.Revealed)
        ClickLoot(panel.reference,item.Key)
        assert(panel.view.SelectedIcon.gameObject.activeSelf and panel.view.SelectedIcon.color.r<.1 and panel.view.ItemName.text=='未搜索的物品')
        panel:Tick(0,0)
        CaptureLoot(panel.reference,'search-in-progress')
    end)
    test('unscaled search reveals sequentially without cancelling a cross-panel pointer drag',function()
        panel:Tick(0,.7);local first,second=session:GetAt(0),session:GetAt(1)
        assert(first.Revealed and not second.Revealed and second.Progress==0)
        BeginLootDrag(panel.reference,first.Key,10,5,false)
        CheckLootDrag(panel.reference,true);CaptureLoot(panel.reference,'dragging-item')
        panel:Tick(0,1.2);assert(second.Revealed and not session:GetAt(2).Revealed)
        CheckLootDrag(panel.reference,true)
        EndLootDrag()
        CheckLootDrag(panel.reference,false)
        local place=eq.data.Grid:GetAt(eq.data.Grid.Count-1)
        assert(first.Count==0 and eq.data.WeaponCount==2 and place.X==10 and place.Y==5 and not source.Looted)
        panel:Tick(0,.35);assert(session:GetAt(2).Progress>0)
        panel.view.Close.onClick:Invoke();assert(not adapter.open and not Services.UI.IsWorldPaused and not session.Active)
        assert(adventure:AreaCommand('area_loot',source.Id));panel=ui:Open('Loot',{demo=adapter});session:Present()
        assert(session:GetAt(0).Count==0 and session:GetAt(1).Revealed and session:GetAt(2).Progress>0 and not session:GetAt(2).Revealed)
    end)
    test('cancelled pointer drop preserves loot; same-item stack drop merges without adding cells',function()
        panel:Tick(0,1);local stack=session:GetAt(1);assert(stack.Revealed)
        local revision=eq.data.Revision;DragLoot(panel.reference,stack.Key,0,0,true)
        CheckLootDrag(panel.reference,false)
        assert(eq.data.Revision==revision and stack.Count==7)
        local old=eq.data.Grid:Find('s31');local cells=eq.data.Grid.Count
        DragLoot(panel.reference,stack.Key,old.X,old.Y,false)
        assert(stack.Count==0 and eq.data:CountItem(31)==19 and eq.data.Grid.Count==cells)
        local weapon=eq.data:GetWeaponAt(0);local key='w'..weapon.Id
        BeginLootDrag(panel.reference,key,8,0,false);CheckLootDrag(panel.reference,true);EndLootDrag();CheckLootDrag(panel.reference,false)
        local place=eq.data.Grid:Find(key);assert(place.X==8 and place.Y==0,'Left backpack must still support ordinary item moves')
        for _=1,4 do panel:Tick(0,1.2) end
        ClickLoot(panel.reference,session:GetAt(2).Key)
        assert(panel.view.SelectedIcon.gameObject.activeSelf and panel.view.SelectedIcon.color.r==1 and panel.view.ItemName.text==eq.rules.items:Get(51).name)
        CaptureLoot(panel.reference,'revealed-items')
        BeginLootDrag(panel.reference,session:GetAt(2).Key,6,6,false);CheckLootDrag(panel.reference,true)
        ui:Back();assert(not adapter.open and not Services.UI.IsWorldPaused)
        CheckLootDrag(panel.reference,false);EndLootDrag()
    end)
    test('empty battle settlement has a usable close action and releases the pause lease',function()
        eq.worldLoot:OpenBattle(areas,state.LootCount,'战斗胜利 · 本次没有物品掉落')
        panel=ui:Open('Loot',{demo=adapter});session:Present()
        assert(#panel.lootRows==0 and panel.view.Empty.text~='' and session.Battle)
        panel.view.Close.onClick:Invoke();assert(not ui:IsOpen('Loot') and not Services.UI.IsWorldPaused)
    end)
    test('real right-grid pointer drops move items, reject collisions and persist backpack deposits after reopening',function()
        state:AddLoot(state.CellIndex,1,'双向拖拽检查',{53},{1},true);local container=state:GetLootAt(state.LootCount-1)
        assert(adventure:AreaCommand('area_loot',container.Id));panel=ui:Open('Loot',{demo=adapter});session:Present();panel:Tick(0,1.2)
        local ring=session:GetAt(0)
        DropInLoot(panel.reference,ring.Key,4,0,false)
        assert(session.Grid:Find(ring.Key).X==4 and session.Grid:Find(ring.Key).Y==0)
        local weapon=eq.data:GetWeaponAt(0);local key='w'..weapon.Id;local place=eq.data.Grid:Find(key)
        DropInLoot(panel.reference,key,0,0,false)
        local stored=session:GetAt(session.Count-1)
        assert(eq.data.Grid:Find(key)==nil and stored.Revealed and session.Grid:Find(stored.Key).X==0)
        local revision=eq.data.Revision;local helmet=eq.data:GetWearableAt(0)
        DropInLoot(panel.reference,'g'..helmet.Id,0,0,false)
        assert(eq.data.Revision==revision and eq.data.Grid:Find('g'..helmet.Id))
        ui:Close('Loot');assert(adventure:AreaCommand('area_loot',container.Id));panel=ui:Open('Loot',{demo=adapter});session:Present()
        assert(session.Grid:Find(ring.Key).X==4 and session.Grid:Find(stored.Key).X==0)
        DragLoot(panel.reference,stored.Key,place.X,place.Y,false)
        assert(eq.data:GetWeapon(weapon.Id)==weapon and eq.data.Grid:Find(key).X==place.X)
        CaptureLoot(panel.reference,'bidirectional-container');ui:Close('Loot')
    end)
    test('battle source dropdown routes deposits to the chosen enemy container only',function()
        local first=state.LootCount;state:AddLoot(state.CellIndex,1,'敌人甲',{},{},true);state:AddLoot(state.CellIndex,1,'敌人乙',{},{},true)
        eq.worldLoot:OpenBattle(areas,first,'选择存放目标');panel=ui:Open('Loot',{demo=adapter});session:Present()
        local revision=eq.data.Revision;DropInLoot(panel.reference,'s31',2,0,false)
        assert(eq.data.Revision==revision and session.SelectedContainerId==0)
        panel.view.Sources.value=2
        assert(session.SelectedContainerId==session:GetContainerAt(1).Id)
        DropInLoot(panel.reference,'s31',2,0,false)
        assert(eq.data:CountItem(31)==0 and session:GetContainerAt(0).ItemCount==0 and session:GetContainerAt(1):GetCountAt(0)==19)
        CaptureLoot(panel.reference,'battle-container-selection');ui:Close('Loot')
    end)
end,debug.traceback)
registry:Shutdown();if not ok then error(err,0) end
return table.concat(results,'\n')
