from pathlib import Path
import json,html,re
from collections import Counter
from PIL import Image,ImageDraw,ImageFont
base=Path(__file__).parent
groups=['Terrain','Dungeon','Items','Weapons','Shipwreck','ShipwreckV2','ShipwreckProps','ShipwreckWeapons']
assets=[];summary={}
for group in groups:
    p=base/group/'manifest.json'
    if not p.exists():continue
    rows=json.loads(p.read_text(encoding='utf8'));summary[group]=len(rows)
    for r in rows:
        refs=[]
        for ref in r.get('references',[]):
            if isinstance(ref,str):continue
            refs.append(dict(work=ref.get('work',ref.get('title','参考作品')),url=ref.get('page',ref.get('page_url','')),
                             image=ref.get('image',ref.get('image_url','')),study=ref.get('study',ref.get('influence_zh',ref.get('notes',ref.get('takeaway',''))))))
        r['gallery_group']=group
        r['gallery_title']=r.get('title',r.get('display_name_zh',r.get('display_name',r.get('name_zh',r['name']))))
        r['gallery_lore']=r.get('lore',r.get('lore_zh',r.get('background_zh','')))
        literary=r.get('literary_reference',r.get('literature_reference',''))
        r['gallery_literature']=literary if isinstance(literary,str) else literary.get('title',literary.get('work',''))
        r['gallery_refs']=refs
        r['gallery_views']=[dict(label=label,path=f'{group}/Previews/{r["name"]}_{v}.png') for v,label in [('front','正面'),('side','侧面'),('back','背面'),('hero','斜视')] if (base/group/'Previews'/f'{r["name"]}_{v}.png').exists()]
        r['gallery_hero']=f'{group}/Previews/{r["name"]}_hero.png'
        r['gallery_fbx']=f'{group}/Staging/{r["name"]}.fbx'
        r['gallery_unity']=f'{group}/UnityPreviews/{r["name"]}.png'
        assets.append(r)
textures_path=base/'Dungeon/texture_manifest.json'
textures=json.loads(textures_path.read_text(encoding='utf8')) if textures_path.exists() else []
payload=json.dumps(dict(assets=assets,textures=textures,summary=summary),ensure_ascii=False).replace('</','<\\/')
template='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project Y · 十月资产档案</title>
<style>*{box-sizing:border-box}body{margin:0;background:#131819;color:#e7e7db;font:15px/1.65 "Microsoft YaHei",sans-serif}header{padding:44px 5vw 24px;border-bottom:1px solid #35403c;background:linear-gradient(100deg,#233b32,#182220)}.eyebrow{font-size:12px;letter-spacing:3px;color:#b8bc8e}h1{font-size:34px;margin:8px 0;font-weight:500}header p{color:#bac6bd;max-width:920px}.counts{display:flex;gap:30px;color:#dfc897}.counts b{font-size:25px}nav{padding:20px 5vw;position:sticky;top:0;background:#131819f0;backdrop-filter:blur(12px);display:flex;gap:10px;flex-wrap:wrap;z-index:3}button,input,select{font:inherit;color:inherit;background:#222c2a;border:1px solid #46584b;border-radius:6px;padding:8px 15px}button{cursor:pointer}button.on{background:#748362;color:#101710}input{min-width:270px;flex:1}main{padding:0 5vw 50px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(215px,1fr));gap:18px}.card{background:#20292a;border:1px solid #34413c;border-radius:9px;overflow:hidden;cursor:pointer;text-align:left;padding:0}.card img{width:100%;aspect-ratio:1;object-fit:contain;background:#3c444e}.card strong,.card small{display:block;padding:0 14px}.card strong{padding-top:10px;font-size:16px}.card small{color:#a0aea3;font-size:11px;padding-bottom:13px}.card:hover{border-color:#bcaa76;transform:translateY(-2px)}.status{font-size:13px;color:#9cad9f;padding-bottom:14px}dialog{width:min(1240px,94vw);max-height:92vh;border:1px solid #5b6b56;background:#182122;color:#e7e7db;padding:26px;border-radius:10px}dialog::backdrop{background:#050a0ada}.close{float:right}.views{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.views img{width:100%;background:#3c444e}.views figcaption{font-size:12px;color:#b9c2b7}.views figure{margin:0}h2{font-weight:500;font-size:25px;margin:0 0 8px}.id{color:#9bad9d;font:12px monospace}.lore{line-height:1.95;max-width:950px}.details{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:24px}.details a,a{color:#d9c38e}h3{font-size:16px;font-weight:500;color:#c8d0c0}.ref{margin-bottom:12px;border-left:2px solid #59684f;padding-left:12px}.note{font-size:13px;color:#a6b2a8}footer{padding:25px 5vw;color:#93a293;font-size:12px;border-top:1px solid #34413c}@media(max-width:700px){.views{grid-template-columns:repeat(2,1fr)}.details{grid-template-columns:1fr}.counts{gap:14px}h1{font-size:27px}}</style>
<header><div class="eyebrow">PROJECT Y / ASSET ARCHIVE / OCTOBER 2026</div><h1>荒野、遗迹与远行者的行囊</h1><p>独立资源库：五类生态、地牢陈设与墙地纹理、中世纪奇幻武器和随身物品。点击资产查看正侧背三视图、原创背景和参考来源。</p><div class="counts" id="counts"></div><p class="note">源文件、FBX、材质与 Prefab 已独立归档。沉船专题已接入开阔水域选址和独立船形小地图；其余初始素材保持独立资源库。地牢新纹理仍需渲染接入。</p></header>
<nav id="nav"><button class="on" data-filter="all">全部</button><button data-filter="Terrain">地形与生态</button><button data-filter="Dungeon">地牢陈设</button><button data-filter="Items">物品与防具</button><button data-filter="Weapons">武器与配件</button><button data-filter="Shipwreck">沉船旧版</button><button data-filter="ShipwreckV2">三层沉船</button><button data-filter="ShipwreckProps">船用小物</button><button data-filter="ShipwreckWeapons">海难武器</button><button data-filter="Textures">墙地纹理</button><input id="search" placeholder="搜索名称、类型、故事…"><select id="category"><option value="">所有类型</option></select></nav>
<main><p class="note"><a href="ShipwreckV2/Previews/sail-enlarged-overview.png" target="_blank">暮潮号 · 真实生成预览</a> · <a href="ShipwreckV2/Previews/navigation_layers.svg" target="_blank">船形导航</a> · <a href="ShipwreckV2/README.md">三层沉船专题档案</a></p><div id="status" class="status"></div><div id="grid" class="grid"></div></main><dialog id="modal"><button class="close" onclick="document.getElementById('modal').close()">关闭 ×</button><div id="detail"></div></dialog><footer>审核证据：各组 Previews、review 文件、manifest.json 与 unity_validation.json。参考图保留原作品版权，仅用于视觉研究；交付模型与纹理为本批原创制作。外部参考链接需要联网。</footer>
<script>const DATA=__DATA__;const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let filter=location.hash.slice(1)||'all';const grid=document.getElementById('grid'),search=document.getElementById('search'),category=document.getElementById('category');
document.getElementById('counts').innerHTML=`<span><b>${DATA.assets.length}</b> 模型</span><span><b>${DATA.textures.length}</b> 纹理</span><span><b>${DATA.assets.reduce((s,a)=>s+a.gallery_views.length,0)}</b> 审核视图</span>`;
[...new Set(DATA.assets.map(a=>a.category))].sort().forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;category.append(o)});
function draw(){let q=search.value.toLowerCase();if(filter==='Textures'){let rows=DATA.textures.filter(t=>(t.id+' '+t.prompt).toLowerCase().includes(q));grid.innerHTML=rows.map(t=>`<button class="card" data-texture="${escape(t.id)}"><img loading="lazy" src="Dungeon/${escape(t.file)}"><strong>${escape(t.id.replace('DG_Tex_',''))}</strong><small>${t.dimensions.join(' × ')} · Repeat / sRGB</small></button>`).join('');document.getElementById('status').textContent=rows.length+' 张墙地纹理；详情可打开 3×3 平铺图';return}let rows=DATA.assets.filter(a=>(filter==='all'||a.gallery_group===filter)&&(!category.value||a.category===category.value)&&JSON.stringify(a).toLowerCase().includes(q));grid.innerHTML=rows.map(a=>`<button class="card" data-name="${escape(a.name)}"><img loading="lazy" src="${escape(a.gallery_hero)}"><strong>${escape(a.gallery_title)}</strong><small>${escape(a.category)} · ${a.triangles} tris</small></button>`).join('');document.getElementById('status').textContent=rows.length+' 件 / 点击查看档案';}
function show(a){document.getElementById('detail').innerHTML=`<h2>${escape(a.gallery_title)}</h2><div class="id">${escape(a.name)}</div><p class="note">${escape(a.category)} · ${a.triangles} triangles · ${escape(a.dimensions_blender_xyz?.map(n=>n.toFixed(3)).join(' × '))} m（Blender XYZ）</p><div class="views">${a.gallery_views.map(v=>`<figure><a href="${escape(v.path)}" target="_blank"><img src="${escape(v.path)}"></a><figcaption>${v.label}</figcaption></figure>`).join('')}</div>${a.gallery_lore?`<h3>物品背景</h3><p class="lore">${escape(a.gallery_lore)}</p>`:`<p class="lore">${escape(a.design_zh||a.design_notes||'')}</p>`}<div class="details"><section><h3>视觉参考</h3>${a.gallery_refs.map(r=>`<div class="ref"><a href="${escape(r.url)}" target="_blank">${escape(r.work)}</a> · <a href="${escape(r.image)}" target="_blank">参考图</a><div class="note">${escape(r.study)}</div></div>`).join('')}</section><section><h3>交付与核验</h3><p><a href="${escape(a.gallery_fbx)}">FBX 模型</a> · <a href="${escape(a.gallery_unity)}" target="_blank">Unity 实际预览 / 图标</a> · <a href="${a.gallery_group}/manifest.json">完整清单</a></p><p class="note">正侧背与斜视来自同一真实网格。闭合/退化面与 Unity 尺寸、材质检查见该组的验证文件。装配仍需按实际角色、挂点与使用方式核对。</p><p class="note">${escape(a.gallery_literature||'')}</p></section></div>`;document.getElementById('modal').showModal();}
grid.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.name)show(DATA.assets.find(a=>a.name===b.dataset.name));else{let t=DATA.textures.find(t=>t.id===b.dataset.texture);document.getElementById('detail').innerHTML=`<h2>${escape(t.id)}</h2><p>${escape(t.seam_status)}</p><div class="views" style="grid-template-columns:1fr 1fr"><img src="Dungeon/${escape(t.file)}"><img src="Dungeon/Previews/${escape(t.id)}_repeat3x3.png"></div><p class="note">平铺保留真实边缘残差；详细数值见纹理清单。游戏随机地图未接入。</p><p><a href="Dungeon/texture_manifest.json">纹理清单与参考来源</a></p>`;document.getElementById('modal').showModal()}};
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;history.replaceState(null,'','#'+filter);document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('on',x===b));category.value='';draw()});search.oninput=draw;category.onchange=draw;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('on',x.dataset.filter===filter));draw();</script></html>'''
(base/'gallery.html').write_text(template.replace('__DATA__',payload),encoding='utf8')
(base/'catalog.json').write_text(json.dumps(dict(counts=summary,models=len(assets),textures=len(textures),assets=assets),ensure_ascii=False,indent=2),encoding='utf8')
print(dict(groups=summary,models=len(assets),textures=len(textures)))
