-- 系统统一注册入口；依赖关系决定初始化顺序，关闭时按相反顺序释放。
return function(registry)
    registry:Register('Config', require('Config.ConfigSystem'))
    registry:Register('Localization', require('Config.LocalizationSystem'), { 'Config' })
    registry:Register('PlayerModel', require('Game.PlayerModelSystem'), { 'Config' })
    registry:Register('Map', require('Game.Map.MapSystem'), { 'Config' })
    registry:Register('MapArea', require('Game.MapArea.MapAreaSystem'), { 'Config' })
    registry:Register('Battle', require('Game.Battle.BattleSystem'), { 'Config' })
    registry:Register('Equipment', require('Game.Equipment.EquipmentSystem'), { 'Config' })
    registry:Register('Growth', require('Game.Progression.GrowthSystem'), { 'Battle' })
    registry:Register('AdventureEvents', require('Game.Adventure.EventSystem'), { 'Battle', 'PlayerModel', 'Growth','Equipment' })
    registry:Register('Adventure', require('Game.Adventure.AdventureSystem'), { 'Map', 'MapArea', 'AdventureEvents', 'Equipment' })
    registry:Register('GM', require('Game.GM.GMSystem'), { 'Config', 'Growth' })
    registry:Register('UI', require('UI.UISystem'), { 'PlayerModel', 'Localization','GM' })
end
