// UI metadata only. Source schemas, refs and Catalog remain the data contract.
export const modules = [
  {id:'items',name:'武器与物品',icon:'◇',description:'从模型开始，定义一件可进入世界的物品。',tables:['EquipmentItemTable','EquipmentWeaponTable','EquipmentWearableTable','EquipmentRuneTable','EquipmentMagazineTable','EquipmentAssetTable','EquipmentSocketTable','EquipmentGripTable','EquipmentHoldAdjustmentTable','EquipmentRequirementTable','EquipmentAttributeTable','EquipmentCategoryTable','EquipmentMotionModuleTable','EquipmentMotionMatchTable','EquipmentPoseTable','EquipmentActionTable']},
  {id:'characters',name:'角色与 NPC',icon:'♙',description:'身份、初始能力、装备与生活在世界中的位置。',tables:['NpcTable','CombatUnitTable','GrowthProfileTable','CharacterLoadoutTable','PawnTemplateTable','MapAreaTownNpcTable','CharacterAppearancePoolTable','NpcPlacementTable','NpcScheduleTable','FactionTable']},
  {id:'missions',name:'任务与对话',icon:'⑂',description:'把人物、条件、任务阶段和奖励连成故事。',tables:['MissionTable','QuestTable','DialogueTable','DialogueNodeTable','DialogueChoiceTable','ConditionTable','NarrativeActionTable','DialogueCameraTable','NarrativeSettingsTable']},
  {id:'abilities',name:'技能与特质',icon:'✧',description:'属性、技能、效果、天赋与角色成长。',tables:['CombatSkillTable','CombatEffectTable','CombatTraitTable','GrowthAttributeTable','TalentTreeTable','TalentNodeTable','GrowthLevelTable','GrowthRuleTable','SkillPoolTable']},
  {id:'world',name:'投放与流程',icon:'◎',description:'明确选择物品来源、奖励、掉落与探索事件。',tables:['AdventureChoiceTable','AdventureEventTable','ExplorationEventTable','EquipmentLootTable','LootPoolTable','LootEntryTable','EnemyDropTable','MapAreaChestRuleTable','MapAreaTownFacilityTable','AdventureDemoTable','EquipmentDemoTable']},
];
export const labels = {EquipmentItemTable:'物品',EquipmentWeaponTable:'武器规则',EquipmentWearableTable:'穿戴与加成',EquipmentRuneTable:'配件特性',EquipmentMagazineTable:'弹匣',EquipmentAssetTable:'模型资源',EquipmentGripTable:'几何握点',EquipmentHoldAdjustmentTable:'持握朝向',EquipmentRequirementTable:'属性要求',EquipmentSocketTable:'改装挂点',NpcTable:'特殊 NPC',CombatUnitTable:'角色能力',GrowthProfileTable:'初始特质与天赋',CharacterLoadoutTable:'初始装备',PawnTemplateTable:'角色外观规则',NpcPlacementTable:'NPC 安置',NpcScheduleTable:'日程',MissionTable:'任务',QuestTable:'任务阶段',DialogueTable:'对话',DialogueNodeTable:'对白节点',DialogueChoiceTable:'对话选项',ConditionTable:'条件',NarrativeActionTable:'奖励与动作',CombatTraitTable:'特质',CombatSkillTable:'技能',CombatEffectTable:'技能效果',AdventureChoiceTable:'商店与事件选项',LootEntryTable:'掉落内容',LootPoolTable:'掉落池',EquipmentLootTable:'战利品容器'};
export function moduleFor(name){return modules.find(m=>m.tables.includes(name))?.id||'all';}
export const optionalReferences={CharacterLoadoutTable:{weaponId:'EquipmentWeaponTable',offhandWeaponId:'EquipmentWeaponTable'},EquipmentWeaponTable:{magazineItemId:'EquipmentMagazineTable',offhandSkillId:'CombatSkillTable'},DialogueChoiceTable:{nextNodeId:'DialogueNodeTable'}};
